import React from "react";
import { ProjectEnvironmentsContext } from "@/context";

export function useProjectEnvironments() {
  const {
    environments,
    setEnvironments,
    loading,
    setLoading,
    error,
    setError,
    selectedEnvironment,
    setSelectedEnvironment,
    showSecrets,
    setShowSecrets,
    environmentDetailsOpen,
    setEnvironmentDetailsOpen,
    activeTab,
    setActiveTab,
    envText,
    setEnvText,
    isSaving,
    setIsSaving,
    copiedSecrets,
    setCopiedSecrets,
    dialogToOpen,
    setDialogToOpen,
    viewingEnvironmentSlug,
    // Functions
    fetchEnvironments,
    handleViewEnvironment,
    handleCopyAllSecrets,
    handleCopySecret,
    handleSaveEnvironment,
  } = React.useContext(ProjectEnvironmentsContext);
  return {
    environments,
    setEnvironments,
    loading,
    setLoading,
    error,
    setError,
    selectedEnvironment,
    setSelectedEnvironment,
    showSecrets,
    setShowSecrets,
    environmentDetailsOpen,
    setEnvironmentDetailsOpen,
    activeTab,
    setActiveTab,
    envText,
    setEnvText,
    isSaving,
    setIsSaving,
    copiedSecrets,
    setCopiedSecrets,
    dialogToOpen,
    setDialogToOpen,
    viewingEnvironmentSlug,
    // Functions
    fetchEnvironments,
    handleViewEnvironment,
    handleCopyAllSecrets,
    handleCopySecret,
    handleSaveEnvironment,
  };
}
